
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "../components/ui/sidebar";
import { AppSidebar } from "../components/app-sidebar";
import { NavBar } from "../components/nav-bar";
// Toaster (Sonner)
import { Toaster } from "../components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  const isLogin = pathname.startsWith("/login");
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        {isLogin ? (
          <main className="min-h-screen">{children}</main>
        ) : (
          <SidebarProvider>
            <NavBar />
            <div className="flex min-h-screen">
              <AppSidebar />
              <main className="flex-1 p-6 sm:p-10">
                {children}
              </main>
              {/* Global toaster for notifications */}
              <Toaster />
            </div>
          </SidebarProvider>
        )}
      </body>
    </html>
  );
}
